import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import { toast } from "react-toastify";

/**
 * Export receipt HTML to a single-page continuous 80mm thermal receipt PDF
 * with full Arabic text shaping, connected letters, and RTL support.
 *
 * @param {Object} receiptData - Receipt metadata and items
 * @param {string} rawHtml - HTML string generated by formatCashierReceipt
 * @returns {Promise<boolean>}
 */
export const downloadReceiptPdf = async (receiptData, rawHtml) => {
  let iframe = null;
  try {
    const cashierLang =
      receiptData?.cashier_lang ||
      localStorage.getItem("cashier_lang") ||
      "ar";
    const isArabic = cashierLang === "ar";
    const invoiceNo = receiptData?.invoiceNumber || receiptData?.id || Date.now();
    const fileName = `Invoice-${invoiceNo}.pdf`;

    if (!rawHtml) {
      console.warn("downloadReceiptPdf: rawHtml is missing");
      return false;
    }

    // Override styles to enforce Arabic cursive ligatures (letter-spacing: normal is critical)
    const overrideStyles = `
      <style>
        * {
          box-sizing: border-box !important;
          -webkit-font-smoothing: antialiased;
        }
        body, html {
          margin: 0 !important;
          padding: 0 !important;
          background-color: #ffffff !important;
          color: #000000 !important;
          font-family: 'Cairo', 'Segoe UI', Tahoma, Arial, sans-serif !important;
        }
        #receipt-pdf-render-container,
        #receipt-pdf-render-container * {
          font-family: 'Cairo', 'Segoe UI', Tahoma, Arial, sans-serif !important;
          letter-spacing: normal !important;
          word-spacing: normal !important;
          box-sizing: border-box !important;
        }
        #receipt-pdf-render-container .header h1,
        #receipt-pdf-render-container h1,
        #receipt-pdf-render-container .section-header {
          letter-spacing: normal !important;
          text-transform: none !important;
        }
        #receipt-pdf-render-container .container {
          width: 100% !important;
          padding: 0 !important;
          margin: 0 !important;
        }
        #receipt-pdf-render-container img {
          max-width: 90px !important;
          height: auto !important;
        }
      </style>
    `;

    // Extract body content if input is a complete HTML document
    let contentToRender = rawHtml;
    const bodyMatch = rawHtml.match(/<body[^>]*>([\s\S]*)<\/body>/i);
    if (bodyMatch) {
      const styleMatches = rawHtml.match(/<style[^>]*>([\s\S]*?)<\/style>/gi) || [];
      contentToRender = styleMatches.join("\n") + overrideStyles + bodyMatch[1];
    } else {
      contentToRender = overrideStyles + rawHtml;
    }

    // Create an isolated hidden iframe completely decoupled from Tailwind v4 / oklch styles
    iframe = document.createElement("iframe");
    iframe.id = "receipt-pdf-render-frame";
    iframe.style.position = "fixed";
    iframe.style.top = "0";
    iframe.style.left = "0";
    iframe.style.width = "340px";
    iframe.style.height = "1200px";
    iframe.style.border = "none";
    iframe.style.zIndex = "-99999";
    iframe.style.opacity = "0";
    iframe.style.pointerEvents = "none";

    document.body.appendChild(iframe);

    const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
    iframeDoc.open();
    iframeDoc.write(`<!DOCTYPE html>
<html dir="${isArabic ? "rtl" : "ltr"}">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800;900&display=swap">
  ${overrideStyles}
</head>
<body dir="${isArabic ? "rtl" : "ltr"}" style="margin: 0; padding: 0; background: #ffffff; color: #000000;">
  <div id="receipt-pdf-render-container" dir="${isArabic ? "rtl" : "ltr"}" style="width: 340px; max-width: 340px; background-color: #ffffff; color: #000000; font-family: 'Cairo', 'Segoe UI', Tahoma, Arial, sans-serif; direction: ${isArabic ? "rtl" : "ltr"}; text-align: ${isArabic ? "right" : "left"}; padding: 6px; box-sizing: border-box;">
    ${contentToRender}
  </div>
</body>
</html>`);
    iframeDoc.close();

    const targetElement = iframeDoc.getElementById("receipt-pdf-render-container") || iframeDoc.body;

    // Wait for fonts inside iframe
    if (iframeDoc.fonts && iframeDoc.fonts.ready) {
      try {
        await iframeDoc.fonts.ready;
      } catch (e) {}
    }

    // Wait for images inside iframe to load
    const images = targetElement.getElementsByTagName("img");
    for (const img of images) {
      img.crossOrigin = "anonymous";
    }

    if (images.length > 0) {
      await Promise.all(
        Array.from(images).map((img) => {
          if (img.complete) return Promise.resolve();
          return new Promise((resolve) => {
            img.onload = resolve;
            img.onerror = () => {
              img.style.display = "none";
              resolve();
            };
            setTimeout(resolve, 800);
          });
        })
      );
    }

    // Short layout settle timeout
    await new Promise((resolve) => setTimeout(resolve, 150));

    // Render DOM to high-DPI canvas (scale 3 = crisp 300+ DPI text)
    const canvas = await html2canvas(targetElement, {
      scale: 3,
      useCORS: true,
      allowTaint: false,
      logging: false,
      backgroundColor: "#ffffff",
      windowWidth: 340,
      onclone: (clonedDoc) => {
        // Strip any unsupported colors in cloned document as a safeguard
        const allElements = clonedDoc.getElementsByTagName("*");
        for (let i = 0; i < allElements.length; i++) {
          const el = allElements[i];
          if (el.style) {
            ["color", "backgroundColor", "borderColor"].forEach((prop) => {
              if (el.style[prop] && el.style[prop].includes("oklch")) {
                el.style[prop] = prop === "backgroundColor" ? "#ffffff" : "#000000";
              }
            });
          }
        }
      },
    });

    const receiptWidthMm = 80;
    const contentHeightMm = (canvas.height * receiptWidthMm) / canvas.width;
    // In portrait mode, jsPDF expects height >= width (80mm).
    // This prevents jsPDF from auto-swapping width and height on short receipts.
    const pageHeightMm = Math.max(Math.round(contentHeightMm), 80);

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: [receiptWidthMm, pageHeightMm],
      compress: true,
    });

    const imgData = canvas.toDataURL("image/png");
    pdf.addImage(imgData, "PNG", 0, 0, receiptWidthMm, contentHeightMm, undefined, "FAST");
    pdf.save(fileName);

    toast.success(
      isArabic
        ? "📄 تم تحميل الفاتورة PDF بنجاح"
        : "📄 Invoice PDF downloaded successfully"
    );
    return true;
  } catch (error) {
    console.error("❌ downloadReceiptPdf error:", error);
    toast.error(
      receiptData?.cashier_lang === "en"
        ? "❌ Failed to download invoice PDF"
        : "❌ فشل تحميل الفاتورة بصيغة PDF"
    );
    return false;
  } finally {
    if (iframe && iframe.parentNode) {
      iframe.parentNode.removeChild(iframe);
    }
  }
};
