import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import { toast } from "react-toastify";

/**
 * Export receipt HTML to a single-page continuous 80mm thermal receipt PDF
 * with full Arabic text shaping, connected letters, and RTL support.
 *
 * @param {Object} receiptData - Receipt metadata and items
 * @param {string} rawHtml - HTML string generated by formatCashierReceipt
 * @returns {Promise<boolean>}
 */
export const downloadReceiptPdf = async (receiptData, rawHtml) => {
  let printContainer = null;
  try {
    const cashierLang =
      receiptData?.cashier_lang ||
      localStorage.getItem("cashier_lang") ||
      "ar";
    const isArabic = cashierLang === "ar";
    const invoiceNo = receiptData?.invoiceNumber || receiptData?.id || Date.now();
    const fileName = `Invoice-${invoiceNo}.pdf`;

    if (!rawHtml) {
      console.warn("downloadReceiptPdf: rawHtml is missing");
      return false;
    }

    // Ensure Cairo font link exists in document head for online rendering
    if (typeof document !== "undefined" && !document.getElementById("food2go-cairo-font")) {
      const link = document.createElement("link");
      link.id = "food2go-cairo-font";
      link.rel = "stylesheet";
      link.href = "https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800;900&display=swap";
      document.head.appendChild(link);
    }

    // Create off-screen container styled for 80mm thermal paper width (~340px)
    printContainer = document.createElement("div");
    printContainer.id = "receipt-pdf-render-container";
    printContainer.style.position = "fixed";
    printContainer.style.top = "0";
    printContainer.style.left = "0";
    printContainer.style.width = "340px";
    printContainer.style.maxWidth = "340px";
    printContainer.style.backgroundColor = "#ffffff";
    printContainer.style.color = "#000000";
    printContainer.style.zIndex = "-99999";
    printContainer.style.pointerEvents = "none";
    printContainer.style.fontFamily = "'Cairo', 'Segoe UI', Tahoma, Arial, sans-serif";
    printContainer.dir = isArabic ? "rtl" : "ltr";
    printContainer.style.direction = isArabic ? "rtl" : "ltr";
    printContainer.style.textAlign = isArabic ? "right" : "left";
    printContainer.style.padding = "6px";
    printContainer.style.boxSizing = "border-box";

    // Override styles to enforce Arabic cursive ligatures (letter-spacing: normal is critical)
    const overrideStyles = `
      <style>
        #receipt-pdf-render-container,
        #receipt-pdf-render-container * {
          font-family: 'Cairo', 'Segoe UI', Tahoma, Arial, sans-serif !important;
          letter-spacing: normal !important;
          word-spacing: normal !important;
          box-sizing: border-box !important;
          -webkit-font-smoothing: antialiased;
        }
        #receipt-pdf-render-container .header h1,
        #receipt-pdf-render-container h1,
        #receipt-pdf-render-container .section-header {
          letter-spacing: normal !important;
          text-transform: none !important;
        }
        #receipt-pdf-render-container .container {
          width: 100% !important;
          padding: 0 !important;
          margin: 0 !important;
        }
        #receipt-pdf-render-container img {
          max-width: 90px !important;
          height: auto !important;
        }
      </style>
    `;

    // Extract body content if input is a complete HTML document
    let contentToRender = rawHtml;
    const bodyMatch = rawHtml.match(/<body[^>]*>([\s\S]*)<\/body>/i);
    if (bodyMatch) {
      const styleMatches = rawHtml.match(/<style[^>]*>([\s\S]*?)<\/style>/gi) || [];
      contentToRender = styleMatches.join("\n") + overrideStyles + bodyMatch[1];
    } else {
      contentToRender = overrideStyles + rawHtml;
    }

    printContainer.innerHTML = contentToRender;

    // Ensure images have crossOrigin set to prevent canvas tainting
    const images = printContainer.getElementsByTagName("img");
    for (const img of images) {
      img.crossOrigin = "anonymous";
    }

    document.body.appendChild(printContainer);

    // Wait for fonts to be ready
    if (document.fonts && document.fonts.ready) {
      try {
        await document.fonts.ready;
      } catch (e) {
        // ignore font readiness error
      }
    }

    // Wait for images to load or timeout safely
    if (images.length > 0) {
      await Promise.all(
        Array.from(images).map((img) => {
          if (img.complete) return Promise.resolve();
          return new Promise((resolve) => {
            img.onload = resolve;
            img.onerror = () => {
              // If an image fails to load (e.g. CORS block), hide it so canvas doesn't break
              img.style.display = "none";
              resolve();
            };
            setTimeout(resolve, 800);
          });
        })
      );
    }

    // Short layout settle timeout
    await new Promise((resolve) => setTimeout(resolve, 150));

    // Render DOM to high-DPI canvas (scale 3 = crisp 300+ DPI text)
    const canvas = await html2canvas(printContainer, {
      scale: 3,
      useCORS: true,
      allowTaint: false,
      logging: false,
      backgroundColor: "#ffffff",
      windowWidth: 340,
    });

    const receiptWidthMm = 80;
    const contentHeightMm = (canvas.height * receiptWidthMm) / canvas.width;
    // In portrait mode, jsPDF expects height >= width (80mm).
    // This prevents jsPDF from auto-swapping width and height on short receipts.
    const pageHeightMm = Math.max(Math.round(contentHeightMm), 80);

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: [receiptWidthMm, pageHeightMm],
      compress: true,
    });

    const imgData = canvas.toDataURL("image/png");
    pdf.addImage(imgData, "PNG", 0, 0, receiptWidthMm, contentHeightMm, undefined, "FAST");
    pdf.save(fileName);

    toast.success(
      isArabic
        ? "📄 تم تحميل الفاتورة PDF بنجاح"
        : "📄 Invoice PDF downloaded successfully"
    );
    return true;
  } catch (error) {
    console.error("❌ downloadReceiptPdf error:", error);
    toast.error(
      receiptData?.cashier_lang === "en"
        ? "❌ Failed to download invoice PDF"
        : "❌ فشل تحميل الفاتورة بصيغة PDF"
    );
    return false;
  } finally {
    if (printContainer && printContainer.parentNode) {
      printContainer.parentNode.removeChild(printContainer);
    }
  }
};
